name: CI/CD Advanced Julia

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn mlflow dagshub matplotlib seaborn

      - name: Run training script
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          rm -rf mlruns
          python MLProject/modelling_tuning.py

      - name: Get latest MLflow run_id
        run: |
          ID=$(ls -t mlruns/0 | grep -v "meta.yaml" | head -n 1)
          echo "RUN_ID=$ID" >> $GITHUB_ENV
          echo "Ditemukan ID: $ID"

      - name: Install Python dependencies
        run: pip install -r MLProject/requirements.txt

      - name: Build Docker Model
        run: |
          MODEL_DIR=$(find mlruns -name "MLmodel" -exec dirname {} \; | head -n 1)
          
          echo "Building from discovered path: $MODEL_DIR"
          
          if [ -n "$MODEL_DIR" ]; then
            mlflow models build-docker -m "$MODEL_DIR" -n "occupancy-classifier-prod" --install-mlflow
          else
            echo "Error: MLmodel file not found in mlruns directory!"
            exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag occupancy-classifier-prod:latest ${{ secrets.DOCKER_USERNAME }}/room-occupancy:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/room-occupancy:latest